COMMON: &common
  TABLEDAP: http://data-test.ooi.rutgers.edu/erddap/tabledap/
  ERDDAP_URL: http://data-test.ooi.rutgers.edu/erddap
  SERVICES_URL: http://localhost:4000
  DEBUG: False
  CACHE_TYPE: simple
  UI_API_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  SECRET_KEY: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  GOOGLE_ANALYTICS: 'UA-50606390-3'
  REDMINE_URL: 'https://localhost'
  SUBSCRIPTION_SERVER: 'http://localhost:12585'
  SAN_DATA_SERVER: 'http://opendap-devel.ooi.rutgers.edu:8080/opendap/hyrax/'
  TROUBLE_TICKETS: 'https://uframe-cm.ooi.rutgers.edu/login'
  RESET_LOGIN_URL: 'http://localhost:5001/admin/reset'
  UI_APP_IP: 'localhost'
  UI_APP_PORT: 5000

DEVELOPMENT: &development
  <<: *common
  DEBUG: True


